name: flutter_rapid_starter
description: "Flutter template to help devs start building apps faster than ever. It includes general use cases for project"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0



dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  rename_app: ^1.6.1
  flutter_scripts: ^0.0.3
  change_app_package_name: ^1.5.0
  lottie: ^3.0.0
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  go_router: ^14.6.2
  connectivity_plus: ^6.1.1
  flutter_secure_storage: ^9.2.2
  easy_localization: ^3.0.7
  logger: ^2.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:

    - assets/images/
    - assets/animations/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo/app_logo.png"


scripts:
  #To generate native splash screen: dart run flutter_native_splash:create --path=path/to/my/file.yaml
  #To change package name: dart run change_app_package_name:main com.new.package.name
  #To rename app name:  dart run rename_app:main all="My App Name"
  regen_platforms: bash scripts/regen_platforms.sh
  rename_package: bash scripts/rename_package.sh
  generate_icons: flutter pub run flutter_launcher_icons
  generate_files: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner build watch --delete-conflicting-outputs
  buildApk: flutter clean && flutter build apk
  buildAbb: flutter clean && flutter build appbundle
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
